### ISSUE TITLE
Output format "plain" doesn't work

### ISSUE THREAD

**Issue by danielkza** [JBZoo/CI-Report-Converter#23]
Using on Github actions as:

```yaml
      - uses: jbzoo/ci-report-converter@2.9.0
        with:
          input-file: ./build/mypy-report.xml
          input-format: junit
          output-format: plain
```          
it fails:

```
 In Convert.php line 105:
  [JBZoo\CiReportConverter\Commands\Exception]                                 
  Format "plain" not found. See the option "--output-format".                  
  Available options: checkstyle,gitlab-json,github-cli,junit,phpmd-json,phpmn  
  d,pmd-cpd,psalm-json,tc-inspections,tc-tests                                 
Exception trace:
  at /app/src/Commands/Convert.php:105
 JBZoo\CiReportConverter\Commands\Convert->getFormat() at /app/src/Commands/Convert.php:82
 JBZoo\CiReportConverter\Commands\Convert->executeAction() at /app/src/Commands/AbstractCommand.php:50
 JBZoo\CiReportConverter\Commands\AbstractCommand->execute() at /app/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:1009
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /app/ci-report-converter.php:45
 require_once() at /app/ci-report-converter:19
convert [-S|--input-format INPUT-FORMAT] [-I|--input-file [INPUT-FILE]] [-T|--output-format OUTPUT-FORMAT] [-O|--output-file [OUTPUT-FILE]] [-R|--root-path [ROOT-PATH]] [-N|--suite-name SUITE-NAME] [-F|--tc-flow-id [TC-FLOW-ID]] [-Q|--non-zero-code [NON-ZERO-CODE]]
```
